[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"
publish = ["git"]
authors = ["Juhasz Sandor <blackghost1987@gmail.com>"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.12"
thiserror = "1.0"
